name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shared:
    uses: ./.github/workflows/shared.yml
  build:
    runs-on: ubuntu-latest
    needs: shared
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/mcpride-markdig-extensions.sln
    - name: Build release
      run: dotnet build src/mcpride-markdig-extensions.sln --no-restore --configuration Release